// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAstr-RXBtf77gpEkXWYpLvzf8qzYh5sXo',
    appId: '1:962183287334:web:3f31e0d08d8de77ee54ce7',
    messagingSenderId: '962183287334',
    projectId: 'firestoreapagi',
    authDomain: 'firestoreapagi.firebaseapp.com',
    storageBucket: 'firestoreapagi.appspot.com',
    measurementId: 'G-0CQHS159PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmoMQvTYFwIWzAnJ7U9-ilfuAdReKglHY',
    appId: '1:504270433035:android:f9aba323380ff46164100e',
    messagingSenderId: '504270433035',
    projectId: 'tugas1-e82c9',
    storageBucket: 'com.example.m09',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrV8NDKu0cPVi50FhnhqKPjQtQzVk43yc',
    appId: '1:962183287334:ios:ad7509ba0cc21dcbe54ce7',
    messagingSenderId: '962183287334',
    projectId: 'firestoreapagi',
    storageBucket: 'firestoreapagi.appspot.com',
    iosBundleId: 'com.example.firestoreapagi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrV8NDKu0cPVi50FhnhqKPjQtQzVk43yc',
    appId: '1:962183287334:ios:7173929e734fbf00e54ce7',
    messagingSenderId: '962183287334',
    projectId: 'firestoreapagi',
    storageBucket: 'firestoreapagi.appspot.com',
    iosBundleId: 'com.example.firestoreapagi.RunnerTests',
  );
}
